install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment-test.yml
  - source activate arc_activitysim
before_script:
  - mv test/data/arc_asim.h5 data/arc_asim.h5
  - mv test/data/skims.omx data/skims.omx
  - python simulate.py
script:
  - pycodestyle --max-line-length=120 .
  - pytest --cov=. --cov-report=term-missing
