name: arc_activitysim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cytoolz
  - future 
  - numpy
  - pandas
  - pip
  - psutil
  - pytables
  - pytest
  - pytest-cov
  - coveralls
  - pycodestyle
  - pyyaml
  - sphinx
  - sphinx_rtd_theme
  - toolz
  - pip:
    - openmatrix
    - zbox
    #- git+https://github.com/ActivitySim/activitysim.git@master
    - git+https://github.com/danielsclint/activitysim.git@ft_hot_fix_schedule