name: arc_activitysim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cytoolz
  - future 
  - numba
  - numpy
  - pandas
  - pip
  - psutil
  - pyarrow
  - pytables
  - pyyaml
  - pip:
    - openmatrix
    - zbox
    #- git+https://github.com/ActivitySim/activitysim.git@develop
    - git+https://github.com/danielsclint/activitysim.git@ft_trip_schedule_parking_choice
