SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - TAZ
  - household_id
  - income_in_thousands
  - num_nondriving_age_children
  - is_CBD
  - is_urban

LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: TAZ
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 28
OUT_PERIOD: 28

SIZE_TERM_SELECTOR: non_mandatory
