#input data store and skims
input_store: arc_asim.h5
skims_file: skims.omx

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
use_shadow_pricing: False

chunk_size: 100000

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - workplace_location
  #- auto_ownership_simulate

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households

resume_after: #initialize_households

trace_od: [0,0]

skim_time_periods:
    hours:
        - 0
        - 6 # TODO: CHECK
        - 11 # TODO: CHECK
        - 16 # TODO: CHECK
        - 20 # TODO: CHECK
        - 24 # TODO: CHECK
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85
