#input data store and skims
input_store: arc_asim.h5
skims_file: skims.omx

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
use_shadow_pricing: False

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households

skim_time_periods:
    hours:
        - 0
        - 6 # TODO: CHECK
        - 11 # TODO: CHECK
        - 16 # TODO: CHECK
        - 20 # TODO: CHECK
        - 24 # TODO: CHECK
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV
