LOGIT_TYPE: MNL

preprocessor:
  SPEC: stop_frequency_annotate_tours_preprocessor
  DF: tours_merged
  TABLES:
    - persons
    - land_use
    - accessibility
    
CONSTANTS:
  TRANSIT_MODES:
    - WALK_ALLTRN
    - WALK_PRMTRN
    - PNR_ALLTRN
    - PNR_PRMTRN
    - KNR_ALLTRN
    - KNR_PRMTRN
  DRIVE_TO_TRANSIT_MODES:
    - PNR_ALLTRN
    - PNR_PRMTRN
    - KNR_ALLTRN
    - KNR_PRMTRN
  NONMOTORIZED_MODES:
    - WALK
    - BIKE
  SCHOOL_BUS:
    - SCHOOL_BUS    
  SHOP_TOUR: shopping
  MAINT_TOUR: othmaint
  SCHOOL_TOUR: school
  EATOUT_TOUR: eatout
  SOCIAL_TOUR: social
  num_atwork_subtours_map:
    no_subtours: 0
    eat: 1
    business1: 1
    maint: 1
    business2: 2
    eat_business: 2
